# Generated by Django 4.1.5 on 2023-03-07 05:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_article_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='related_likes', to=settings.AUTH_USER_MODEL, verbose_name='Отметки "Нравится"'),
        ),
    ]
