# Generated by Django 4.1.5 on 2023-03-10 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_thread_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content_to_display',
            field=models.TextField(default='<p>asd</p>', verbose_name='HTML-код содержимого'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='thread',
            name='content_to_display',
            field=models.TextField(default=2, verbose_name='HTML-код содержимого'),
            preserve_default=False,
        ),
    ]
