# Generated by Django 4.1.5 on 2023-03-10 04:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_post_content_to_display_thread_content_to_display'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='post_likes', to=settings.AUTH_USER_MODEL, verbose_name='Отметки "Нравится"'),
        ),
        migrations.AddField(
            model_name='thread',
            name='rating',
            field=models.ManyToManyField(blank=True, related_name='related_rating', to=settings.AUTH_USER_MODEL, verbose_name='Рейтинг темы'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='comment_likes', to=settings.AUTH_USER_MODEL, verbose_name='Отметки "Нравится"'),
        ),
    ]
