# Generated by Django 4.1.5 on 2023-03-15 07:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_post_likes_thread_rating_alter_comment_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thread',
            name='rating',
        ),
        migrations.AddField(
            model_name='post',
            name='dislikes',
            field=models.ManyToManyField(blank=True, related_name='post_dislikes', to=settings.AUTH_USER_MODEL, verbose_name='Отметки "Не нравится"'),
        ),
        migrations.AddField(
            model_name='thread',
            name='dislikes',
            field=models.ManyToManyField(blank=True, related_name='thread_dislikes', to=settings.AUTH_USER_MODEL, verbose_name='Отметки "Не нравится"'),
        ),
        migrations.AddField(
            model_name='thread',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='thread_likes', to=settings.AUTH_USER_MODEL, verbose_name='Отметки "Нравится"'),
        ),
    ]
